"""PR-008 source file import migration."""
from document_intake.persistence.migrations.model import Migration, migration_checksum
STATEMENTS = (
"""CREATE TABLE upload_batches(id TEXT PRIMARY KEY CHECK(length(id)=36), number TEXT NOT NULL UNIQUE CHECK(length(number) BETWEEN 1 AND 64 AND substr(number,1,1) GLOB '[A-Z0-9]' AND number NOT GLOB '*[^A-Z0-9_-]*'), created_at_utc TEXT NOT NULL CHECK(substr(created_at_utc,-1)='Z'), created_by_actor_id TEXT NOT NULL CHECK(length(created_by_actor_id)=36), created_by_actor_kind TEXT NOT NULL CHECK(created_by_actor_kind IN ('OPERATOR','ADMIN','SYSTEM')), status TEXT NOT NULL CHECK(status IN ('NEW','PROCESSING','NEEDS_REVIEW','READY','ARCHIVED')), expected_source_file_count INTEGER NOT NULL CHECK(expected_source_file_count>=0), canonical_payload TEXT NOT NULL)""",
"""CREATE TABLE source_files(id TEXT PRIMARY KEY CHECK(length(id)=36), batch_id TEXT NOT NULL REFERENCES upload_batches(id), original_artifact_id TEXT NOT NULL UNIQUE REFERENCES stored_artifacts(artifact_id), original_basename TEXT NOT NULL CHECK(length(original_basename) BETWEEN 1 AND 255 AND original_basename NOT GLOB '*/*' AND original_basename NOT GLOB '*\\*'), detected_media_type TEXT NOT NULL CHECK(detected_media_type IN ('JPEG','PNG','HEIF')), byte_size INTEGER NOT NULL CHECK(byte_size>0), sha256 TEXT NOT NULL CHECK(length(sha256)=64 AND sha256 NOT GLOB '*[^0-9a-f]*'), perceptual_algorithm_id TEXT NOT NULL CHECK(perceptual_algorithm_id='DHASH64'), perceptual_algorithm_version INTEGER NOT NULL CHECK(perceptual_algorithm_version=1), perceptual_bit_width INTEGER NOT NULL CHECK(perceptual_bit_width=64), perceptual_hex_value TEXT NOT NULL CHECK(length(perceptual_hex_value)=16 AND perceptual_hex_value NOT GLOB '*[^0-9a-f]*'), width INTEGER NOT NULL CHECK(width>0), height INTEGER NOT NULL CHECK(height>0), exif_orientation INTEGER NULL CHECK(exif_orientation IS NULL OR exif_orientation BETWEEN 1 AND 8), imported_at_utc TEXT NOT NULL CHECK(substr(imported_at_utc,-1)='Z'), imported_by_actor_id TEXT NOT NULL CHECK(length(imported_by_actor_id)=36), imported_by_actor_kind TEXT NOT NULL CHECK(imported_by_actor_kind IN ('OPERATOR','ADMIN','SYSTEM')), canonical_payload TEXT NOT NULL)""",
"""CREATE TABLE upload_batch_source_files(batch_id TEXT NOT NULL REFERENCES upload_batches(id), order_index INTEGER NOT NULL CHECK(order_index>=0), source_file_id TEXT NOT NULL UNIQUE REFERENCES source_files(id), PRIMARY KEY(batch_id, order_index))""",
"""CREATE INDEX source_files_batch_order_idx ON source_files(batch_id, imported_at_utc, id)""",
"""CREATE INDEX source_files_sha_order_idx ON source_files(sha256, imported_at_utc, id)""",
"""CREATE INDEX source_files_perceptual_order_idx ON source_files(perceptual_algorithm_id, perceptual_algorithm_version, perceptual_bit_width, imported_at_utc, id)""",
"""CREATE INDEX upload_batch_source_files_order_idx ON upload_batch_source_files(batch_id, order_index, source_file_id)""",
)
MIGRATION = Migration(4, "source_file_import_pr008", STATEMENTS, migration_checksum(STATEMENTS))
