"""Core domain enumerations."""

from __future__ import annotations

from enum import StrEnum


class DocumentType(StrEnum):
    PASSPORT = "PASSPORT"
    IDENTITY_CARD = "IDENTITY_CARD"
    DRIVER_LICENSE = "DRIVER_LICENSE"
    MIGRATION_CARD = "MIGRATION_CARD"
    WORK_PERMIT = "WORK_PERMIT"
    TEMPORARY_REGISTRATION = "TEMPORARY_REGISTRATION"
    VEHICLE_REGISTRATION_TRACTOR = "VEHICLE_REGISTRATION_TRACTOR"
    VEHICLE_REGISTRATION_TRAILER = "VEHICLE_REGISTRATION_TRAILER"
    PASSPORT_STAMP_PAGE = "PASSPORT_STAMP_PAGE"
    OTHER = "OTHER"


class DocumentWorkflowStatus(StrEnum):
    NEW = "NEW"
    NEEDS_SEGMENTATION = "NEEDS_SEGMENTATION"
    NEEDS_CLASSIFICATION = "NEEDS_CLASSIFICATION"
    OCR_READY = "OCR_READY"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    VERIFIED = "VERIFIED"
    INCOMPLETE = "INCOMPLETE"
    READY_FOR_EXPORT = "READY_FOR_EXPORT"
    EXPORTED = "EXPORTED"


class VerificationStatus(StrEnum):
    UNVERIFIED = "UNVERIFIED"
    VERIFIED = "VERIFIED"
    CONFLICT = "CONFLICT"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    ADMIN_OVERRIDE = "ADMIN_OVERRIDE"


class CandidateSourceType(StrEnum):
    VISUAL_OCR = "VISUAL_OCR"
    MRZ = "MRZ"
    BARCODE = "BARCODE"
    TEMPLATE_RULE = "TEMPLATE_RULE"
    RELATED_DOCUMENT = "RELATED_DOCUMENT"
    OPERATOR_ENTRY = "OPERATOR_ENTRY"


class ActorKind(StrEnum):
    OPERATOR = "OPERATOR"
    ADMIN = "ADMIN"
    SYSTEM = "SYSTEM"


class VehicleRole(StrEnum):
    TRACTOR = "TRACTOR"
    TRAILER = "TRAILER"
    SEMI_TRAILER = "SEMI_TRAILER"
    OTHER = "OTHER"


class TerminalCode(StrEnum):
    TSP = "TSP"
    VISITORS = "VISITORS"
    MGS = "MGS"


class ApplicationStatus(StrEnum):
    DRAFT = "DRAFT"
    INCOMPLETE = "INCOMPLETE"
    READY_FOR_SNAPSHOT = "READY_FOR_SNAPSHOT"
    SNAPSHOTTED = "SNAPSHOTTED"
    EXPORTED = "EXPORTED"
    FAILED = "FAILED"


class OwnerKind(StrEnum):
    PERSON = "PERSON"
    VEHICLE = "VEHICLE"


class ArtifactKind(StrEnum):
    ORIGINAL = "ORIGINAL"
    PREPARED_DOCUMENT = "PREPARED_DOCUMENT"
    EXPORT_ARTIFACT = "EXPORT_ARTIFACT"


class AuditAction(StrEnum):
    ENTITY_CREATED = "ENTITY_CREATED"
    ENTITY_UPDATED = "ENTITY_UPDATED"
    FIELD_CORRECTED = "FIELD_CORRECTED"
    FIELD_VERIFIED = "FIELD_VERIFIED"
    SNAPSHOT_CREATED = "SNAPSHOT_CREATED"
    ARTIFACT_REGISTERED = "ARTIFACT_REGISTERED"
    EXPORT_CREATED = "EXPORT_CREATED"


class AuditSubjectType(StrEnum):
    PERSON = "PERSON"
    IDENTITY_DOCUMENT = "IDENTITY_DOCUMENT"
    MIGRATION_DOCUMENT = "MIGRATION_DOCUMENT"
    VEHICLE = "VEHICLE"
    DOCUMENT = "DOCUMENT"
    FIELD_CANDIDATE = "FIELD_CANDIDATE"
    APPLICATION = "APPLICATION"
    APPLICATION_SNAPSHOT = "APPLICATION_SNAPSHOT"
    STORED_ARTIFACT = "STORED_ARTIFACT"


class AuditValueClassification(StrEnum):
    ABSENT = "ABSENT"
    NON_SENSITIVE = "NON_SENSITIVE"
    SENSITIVE_REDACTED = "SENSITIVE_REDACTED"


class UploadBatchStatus(StrEnum):
    NEW = "NEW"
    PROCESSING = "PROCESSING"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    READY = "READY"
    ARCHIVED = "ARCHIVED"


class SourceMediaType(StrEnum):
    JPEG = "JPEG"
    PNG = "PNG"
    HEIF = "HEIF"


class ImportWarningCode(StrEnum):
    EXACT_DUPLICATE = "EXACT_DUPLICATE"
    PERCEPTUAL_SIMILARITY = "PERCEPTUAL_SIMILARITY"
    EXTENSION_CONTENT_MISMATCH = "EXTENSION_CONTENT_MISMATCH"


class SourceImportErrorCode(StrEnum):
    BATCH_NOT_FOUND = "BATCH_NOT_FOUND"
    SOURCE_READ_FAILED = "SOURCE_READ_FAILED"
    SOURCE_BASENAME_INVALID = "SOURCE_BASENAME_INVALID"
    UNSUPPORTED_EXTENSION = "UNSUPPORTED_EXTENSION"
    UNSUPPORTED_FORMAT = "UNSUPPORTED_FORMAT"
    DECODE_FAILED = "DECODE_FAILED"
    STORAGE_PUBLICATION_FAILED = "STORAGE_PUBLICATION_FAILED"
    PERSISTENCE_FAILED = "PERSISTENCE_FAILED"
