"""Persistence ports for encrypted local storage."""

from __future__ import annotations

from types import TracebackType
from typing import Protocol, Self

from document_intake.application.dto.storage import StoredArtifactRecord
from document_intake.domain import (
    Application,
    ApplicationSnapshot,
    AuditEvent,
    Document,
    FieldCandidate,
    FieldRef,
    IdentityDocument,
    ImageQualityAssessment,
    MigrationDocument,
    OwnerRef,
    Person,
    SourceFile,
    Terminal,
    TerminalCode,
    UploadBatch,
    Vehicle,
)
from document_intake.domain.enums import AuditSubjectType
from document_intake.domain.value_objects import BatchNumber, EntityId, Sha256Digest


class DatabaseKeyProvider(Protocol):
    def get_database_key(self) -> bytes: ...


class PersonRepository(Protocol):
    def add(self, person: Person) -> None: ...
    def get(self, entity_id: EntityId) -> Person | None: ...
    def update(self, person: Person) -> None: ...
    def list_all(self) -> tuple[Person, ...]: ...


class IdentityDocumentRepository(Protocol):
    def add(self, document: IdentityDocument) -> None: ...
    def get(self, entity_id: EntityId) -> IdentityDocument | None: ...
    def update(self, document: IdentityDocument) -> None: ...
    def list_by_person(self, person_id: EntityId) -> tuple[IdentityDocument, ...]: ...


class MigrationDocumentRepository(Protocol):
    def add(self, document: MigrationDocument) -> None: ...
    def get(self, entity_id: EntityId) -> MigrationDocument | None: ...
    def update(self, document: MigrationDocument) -> None: ...
    def list_by_person(self, person_id: EntityId) -> tuple[MigrationDocument, ...]: ...


class VehicleRepository(Protocol):
    def add(self, vehicle: Vehicle) -> None: ...
    def get(self, entity_id: EntityId) -> Vehicle | None: ...
    def update(self, vehicle: Vehicle) -> None: ...
    def list_all(self) -> tuple[Vehicle, ...]: ...


class TerminalRepository(Protocol):
    def add(self, terminal: Terminal) -> None: ...
    def get(self, code: TerminalCode) -> Terminal | None: ...
    def update(self, terminal: Terminal) -> None: ...
    def list_active(self) -> tuple[Terminal, ...]: ...


class DocumentRepository(Protocol):
    def add(self, document: Document) -> None: ...
    def get(self, entity_id: EntityId) -> Document | None: ...
    def update(self, document: Document) -> None: ...
    def list_by_owner(self, owner_ref: OwnerRef) -> tuple[Document, ...]: ...


class FieldCandidateRepository(Protocol):
    def add(self, candidate: FieldCandidate) -> None: ...
    def get(self, entity_id: EntityId) -> FieldCandidate | None: ...
    def update(self, candidate: FieldCandidate) -> None: ...
    def list_for_field(self, field_ref: FieldRef) -> tuple[FieldCandidate, ...]: ...


class ApplicationRepository(Protocol):
    def add(self, application: Application) -> None: ...
    def get(self, entity_id: EntityId) -> Application | None: ...
    def update(self, application: Application) -> None: ...


class ApplicationSnapshotRepository(Protocol):
    def add(self, snapshot: ApplicationSnapshot) -> None: ...
    def get(self, entity_id: EntityId) -> ApplicationSnapshot | None: ...
    def list_by_application(self, application_id: EntityId) -> tuple[ApplicationSnapshot, ...]: ...


class StoredArtifactRepository(Protocol):
    def add(self, record: StoredArtifactRecord) -> None: ...
    def get(self, artifact_id: EntityId) -> StoredArtifactRecord | None: ...
    def list_all(self) -> tuple[StoredArtifactRecord, ...]: ...


class AuditEventRepository(Protocol):
    def add(self, event: AuditEvent) -> None: ...
    def get(self, event_id: EntityId) -> AuditEvent | None: ...
    def list_for_subject(
        self,
        subject_type: AuditSubjectType,
        subject_id: EntityId,
    ) -> tuple[AuditEvent, ...]: ...
    def list_by_correlation(
        self,
        correlation_id: EntityId,
    ) -> tuple[AuditEvent, ...]: ...


class UploadBatchRepository(Protocol):
    def add(self, batch: UploadBatch) -> None: ...
    def get(self, batch_id: EntityId) -> UploadBatch | None: ...
    def update(self, batch: UploadBatch) -> None: ...
    def get_by_number(self, number: BatchNumber) -> UploadBatch | None: ...


class SourceFileRepository(Protocol):
    def add(self, source_file: SourceFile) -> None: ...
    def get(self, source_file_id: EntityId) -> SourceFile | None: ...
    def list_by_batch(self, batch_id: EntityId) -> tuple[SourceFile, ...]: ...
    def list_by_sha256(self, sha256: Sha256Digest) -> tuple[SourceFile, ...]: ...
    def list_compatible_perceptual_hashes(
        self, algorithm_id: str, algorithm_version: int, bit_width: int
    ) -> tuple[SourceFile, ...]: ...


class ImageQualityAssessmentRepository(Protocol):
    def add(self, assessment: ImageQualityAssessment) -> None: ...
    def get(self, assessment_id: EntityId) -> ImageQualityAssessment | None: ...
    def list_by_source(self, source_file_id: EntityId) -> tuple[ImageQualityAssessment, ...]: ...


class UnitOfWork(Protocol):
    persons: PersonRepository
    identity_documents: IdentityDocumentRepository
    migration_documents: MigrationDocumentRepository
    vehicles: VehicleRepository
    terminals: TerminalRepository
    documents: DocumentRepository
    field_candidates: FieldCandidateRepository
    applications: ApplicationRepository
    application_snapshots: ApplicationSnapshotRepository
    stored_artifacts: StoredArtifactRepository
    audit_events: AuditEventRepository
    upload_batches: UploadBatchRepository
    source_files: SourceFileRepository
    image_quality_assessments: ImageQualityAssessmentRepository

    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class UnitOfWorkFactory(Protocol):
    def unit_of_work(self) -> UnitOfWork: ...
