"""Persistence ports for encrypted local storage."""

from __future__ import annotations

from types import TracebackType
from typing import Protocol, Self

from document_intake.application.dto.storage import StoredArtifactRecord
from document_intake.domain import (
    Application,
    ApplicationSnapshot,
    AuditEvent,
    Document,
    DocumentRegionSetVersion,
    DocumentSideComposition,
    DocumentSideCompositionVersion,
    FieldCandidate,
    FieldRef,
    IdentityDocument,
    ImageGeometryRecipe,
    ImageQualityAssessment,
    MigrationDocument,
    OwnerRef,
    Person,
    PreparedCompositionArtifact,
    PreparedImageArtifact,
    SourceFile,
    Terminal,
    TerminalCode,
    UploadBatch,
    Vehicle,
)
from document_intake.domain.enums import AuditSubjectType, DocumentSideCompositionLayout
from document_intake.domain.value_objects import BatchNumber, EntityId, Sha256Digest


class DatabaseKeyProvider(Protocol):
    def get_database_key(self) -> bytes: ...


class PersonRepository(Protocol):
    def add(self, person: Person) -> None: ...
    def get(self, entity_id: EntityId) -> Person | None: ...
    def update(self, person: Person) -> None: ...
    def list_all(self) -> tuple[Person, ...]: ...


class IdentityDocumentRepository(Protocol):
    def add(self, document: IdentityDocument) -> None: ...
    def get(self, entity_id: EntityId) -> IdentityDocument | None: ...
    def update(self, document: IdentityDocument) -> None: ...
    def list_by_person(self, person_id: EntityId) -> tuple[IdentityDocument, ...]: ...


class MigrationDocumentRepository(Protocol):
    def add(self, document: MigrationDocument) -> None: ...
    def get(self, entity_id: EntityId) -> MigrationDocument | None: ...
    def update(self, document: MigrationDocument) -> None: ...
    def list_by_person(self, person_id: EntityId) -> tuple[MigrationDocument, ...]: ...


class VehicleRepository(Protocol):
    def add(self, vehicle: Vehicle) -> None: ...
    def get(self, entity_id: EntityId) -> Vehicle | None: ...
    def update(self, vehicle: Vehicle) -> None: ...
    def list_all(self) -> tuple[Vehicle, ...]: ...


class TerminalRepository(Protocol):
    def add(self, terminal: Terminal) -> None: ...
    def get(self, code: TerminalCode) -> Terminal | None: ...
    def update(self, terminal: Terminal) -> None: ...
    def list_active(self) -> tuple[Terminal, ...]: ...


class DocumentRepository(Protocol):
    def add(self, document: Document) -> None: ...
    def get(self, entity_id: EntityId) -> Document | None: ...
    def update(self, document: Document) -> None: ...
    def list_by_owner(self, owner_ref: OwnerRef) -> tuple[Document, ...]: ...


class FieldCandidateRepository(Protocol):
    def add(self, candidate: FieldCandidate) -> None: ...
    def get(self, entity_id: EntityId) -> FieldCandidate | None: ...
    def update(self, candidate: FieldCandidate) -> None: ...
    def list_for_field(self, field_ref: FieldRef) -> tuple[FieldCandidate, ...]: ...


class ApplicationRepository(Protocol):
    def add(self, application: Application) -> None: ...
    def get(self, entity_id: EntityId) -> Application | None: ...
    def update(self, application: Application) -> None: ...


class ApplicationSnapshotRepository(Protocol):
    def add(self, snapshot: ApplicationSnapshot) -> None: ...
    def get(self, entity_id: EntityId) -> ApplicationSnapshot | None: ...
    def list_by_application(self, application_id: EntityId) -> tuple[ApplicationSnapshot, ...]: ...


class StoredArtifactRepository(Protocol):
    def add(self, record: StoredArtifactRecord) -> None: ...
    def get(self, artifact_id: EntityId) -> StoredArtifactRecord | None: ...
    def list_all(self) -> tuple[StoredArtifactRecord, ...]: ...


class AuditEventRepository(Protocol):
    def add(self, event: AuditEvent) -> None: ...
    def get(self, event_id: EntityId) -> AuditEvent | None: ...
    def list_for_subject(
        self,
        subject_type: AuditSubjectType,
        subject_id: EntityId,
    ) -> tuple[AuditEvent, ...]: ...
    def list_by_correlation(
        self,
        correlation_id: EntityId,
    ) -> tuple[AuditEvent, ...]: ...


class UploadBatchRepository(Protocol):
    def add(self, batch: UploadBatch) -> None: ...
    def get(self, batch_id: EntityId) -> UploadBatch | None: ...
    def update(self, batch: UploadBatch) -> None: ...
    def get_by_number(self, number: BatchNumber) -> UploadBatch | None: ...


class SourceFileRepository(Protocol):
    def add(self, source_file: SourceFile) -> None: ...
    def get(self, source_file_id: EntityId) -> SourceFile | None: ...
    def list_by_batch(self, batch_id: EntityId) -> tuple[SourceFile, ...]: ...
    def list_by_sha256(self, sha256: Sha256Digest) -> tuple[SourceFile, ...]: ...
    def list_compatible_perceptual_hashes(
        self, algorithm_id: str, algorithm_version: int, bit_width: int
    ) -> tuple[SourceFile, ...]: ...


class ImageGeometryRecipeRepository(Protocol):
    def add(self, recipe: ImageGeometryRecipe) -> None: ...
    def get(self, recipe_version_id: EntityId) -> ImageGeometryRecipe | None: ...
    def get_latest_by_source(self, source_file_id: EntityId) -> ImageGeometryRecipe | None: ...
    def get_by_source_revision(
        self, source_file_id: EntityId, revision: int
    ) -> ImageGeometryRecipe | None: ...
    def list_by_source(self, source_file_id: EntityId) -> tuple[ImageGeometryRecipe, ...]: ...
    def list_by_region(
        self, source_file_id: EntityId, region_id: EntityId
    ) -> tuple[ImageGeometryRecipe, ...]: ...
    def get_latest_by_region(
        self, source_file_id: EntityId, region_id: EntityId
    ) -> ImageGeometryRecipe | None: ...


class DocumentRegionSetRepository(Protocol):
    def add(self, region_set: DocumentRegionSetVersion) -> None: ...
    def get(self, region_set_version_id: EntityId) -> DocumentRegionSetVersion | None: ...
    def list_by_source(self, source_file_id: EntityId) -> tuple[DocumentRegionSetVersion, ...]: ...
    def get_latest_by_source(self, source_file_id: EntityId) -> DocumentRegionSetVersion | None: ...


class ImageQualityAssessmentRepository(Protocol):
    def add(self, assessment: ImageQualityAssessment) -> None: ...
    def get(self, assessment_id: EntityId) -> ImageQualityAssessment | None: ...
    def list_by_source(self, source_file_id: EntityId) -> tuple[ImageQualityAssessment, ...]: ...


class PreparedImageArtifactRepository(Protocol):
    def add(self, artifact: PreparedImageArtifact) -> None: ...
    def get(self, prepared_artifact_id: EntityId) -> PreparedImageArtifact | None: ...
    def get_by_natural_key(
        self,
        geometry_recipe_version_id: EntityId,
        pipeline_id: str,
        pipeline_version: int,
        output_contract_id: str,
        output_contract_version: int,
    ) -> PreparedImageArtifact | None: ...
    def list_by_source(self, source_file_id: EntityId) -> tuple[PreparedImageArtifact, ...]: ...
    def list_by_geometry_recipe(
        self, geometry_recipe_version_id: EntityId
    ) -> tuple[PreparedImageArtifact, ...]: ...


class DocumentSideCompositionRepository(Protocol):
    def add_composition(self, composition: DocumentSideComposition) -> None: ...
    def add_version(self, version: DocumentSideCompositionVersion) -> None: ...
    def add_artifact(self, artifact: PreparedCompositionArtifact) -> None: ...
    def get_composition(self, composition_id: EntityId) -> DocumentSideComposition | None: ...
    def get_version(
        self, composition_version_id: EntityId
    ) -> DocumentSideCompositionVersion | None: ...
    def get_artifact(
        self, prepared_artifact_id: EntityId
    ) -> PreparedCompositionArtifact | None: ...
    def get_artifact_by_composition_version(
        self, composition_version_id: EntityId
    ) -> PreparedCompositionArtifact | None: ...
    def get_by_natural_key(
        self,
        *,
        side_1_region_set_version_id: EntityId,
        side_1_source_file_id: EntityId,
        side_1_region_id: EntityId,
        side_1_geometry_recipe_version_id: EntityId,
        side_2_region_set_version_id: EntityId,
        side_2_source_file_id: EntityId,
        side_2_region_id: EntityId,
        side_2_geometry_recipe_version_id: EntityId,
        layout: DocumentSideCompositionLayout,
        outer_margin_px: int,
        inter_side_gap_px: int,
        composition_pipeline_id: str,
        composition_pipeline_version: int,
        jpeg_pipeline_id: str,
        jpeg_pipeline_version: int,
        output_contract_id: str,
        output_contract_version: int,
    ) -> DocumentSideCompositionVersion | None: ...


class UnitOfWork(Protocol):
    persons: PersonRepository
    identity_documents: IdentityDocumentRepository
    migration_documents: MigrationDocumentRepository
    vehicles: VehicleRepository
    terminals: TerminalRepository
    documents: DocumentRepository
    field_candidates: FieldCandidateRepository
    applications: ApplicationRepository
    application_snapshots: ApplicationSnapshotRepository
    stored_artifacts: StoredArtifactRepository
    audit_events: AuditEventRepository
    upload_batches: UploadBatchRepository
    source_files: SourceFileRepository
    image_quality_assessments: ImageQualityAssessmentRepository
    image_geometry_recipes: ImageGeometryRecipeRepository
    prepared_image_artifacts: PreparedImageArtifactRepository
    document_region_sets: DocumentRegionSetRepository
    document_side_compositions: DocumentSideCompositionRepository

    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...


class UnitOfWorkFactory(Protocol):
    def unit_of_work(self) -> UnitOfWork: ...
