"""Persistence ports for encrypted local storage."""

from __future__ import annotations

from types import TracebackType
from typing import Protocol, Self

from document_intake.domain import (
    Application,
    ApplicationSnapshot,
    Document,
    FieldCandidate,
    FieldRef,
    IdentityDocument,
    MigrationDocument,
    OwnerRef,
    Person,
    Terminal,
    TerminalCode,
    Vehicle,
)
from document_intake.domain.value_objects import EntityId


class DatabaseKeyProvider(Protocol):
    def get_database_key(self) -> bytes: ...


class PersonRepository(Protocol):
    def add(self, person: Person) -> None: ...
    def get(self, entity_id: EntityId) -> Person | None: ...
    def update(self, person: Person) -> None: ...
    def list_all(self) -> tuple[Person, ...]: ...


class IdentityDocumentRepository(Protocol):
    def add(self, document: IdentityDocument) -> None: ...
    def get(self, entity_id: EntityId) -> IdentityDocument | None: ...
    def update(self, document: IdentityDocument) -> None: ...
    def list_by_person(self, person_id: EntityId) -> tuple[IdentityDocument, ...]: ...


class MigrationDocumentRepository(Protocol):
    def add(self, document: MigrationDocument) -> None: ...
    def get(self, entity_id: EntityId) -> MigrationDocument | None: ...
    def update(self, document: MigrationDocument) -> None: ...
    def list_by_person(self, person_id: EntityId) -> tuple[MigrationDocument, ...]: ...


class VehicleRepository(Protocol):
    def add(self, vehicle: Vehicle) -> None: ...
    def get(self, entity_id: EntityId) -> Vehicle | None: ...
    def update(self, vehicle: Vehicle) -> None: ...
    def list_all(self) -> tuple[Vehicle, ...]: ...


class TerminalRepository(Protocol):
    def add(self, terminal: Terminal) -> None: ...
    def get(self, code: TerminalCode) -> Terminal | None: ...
    def update(self, terminal: Terminal) -> None: ...
    def list_active(self) -> tuple[Terminal, ...]: ...


class DocumentRepository(Protocol):
    def add(self, document: Document) -> None: ...
    def get(self, entity_id: EntityId) -> Document | None: ...
    def update(self, document: Document) -> None: ...
    def list_by_owner(self, owner_ref: OwnerRef) -> tuple[Document, ...]: ...


class FieldCandidateRepository(Protocol):
    def add(self, candidate: FieldCandidate) -> None: ...
    def get(self, entity_id: EntityId) -> FieldCandidate | None: ...
    def list_for_field(self, field_ref: FieldRef) -> tuple[FieldCandidate, ...]: ...


class ApplicationRepository(Protocol):
    def add(self, application: Application) -> None: ...
    def get(self, entity_id: EntityId) -> Application | None: ...
    def update(self, application: Application) -> None: ...


class ApplicationSnapshotRepository(Protocol):
    def add(self, snapshot: ApplicationSnapshot) -> None: ...
    def get(self, entity_id: EntityId) -> ApplicationSnapshot | None: ...
    def list_by_application(self, application_id: EntityId) -> tuple[ApplicationSnapshot, ...]: ...


class UnitOfWork(Protocol):
    persons: PersonRepository
    identity_documents: IdentityDocumentRepository
    migration_documents: MigrationDocumentRepository
    vehicles: VehicleRepository
    terminals: TerminalRepository
    documents: DocumentRepository
    field_candidates: FieldCandidateRepository
    applications: ApplicationRepository
    application_snapshots: ApplicationSnapshotRepository

    def __enter__(self) -> Self: ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc: BaseException | None,
        traceback: TracebackType | None,
    ) -> bool: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
